### ISSUE TITLE
Worldgen crash

### ISSUE THREAD

**Issue by ODevil97** [LunaPixelStudios/SteamPunk#210]
### Describe the Bug

Server crashes randomly when exploring overworld.
Luckily, the issue does not persist after restarting the server.
`[07Apr2024 21:04:12.941] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.IllegalStateException: Chunk not there when requested: UNLOADED
	at net.minecraft.server.level.ServerChunkCache.m_8421_(ServerChunkCache.java:135) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-5.0.28.jar%2375!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.level.Level.m_6522_(Level.java:179) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:129) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.level.Level.m_6325_(Level.java:174) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.level.Level.m_8055_(Level.java:352) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater$MultiNeighborUpdate.m_213563_(CollectingNeighborUpdater.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_230645_(CollectingNeighborUpdater.java:78) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_230660_(CollectingNeighborUpdater.java:65) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_214152_(CollectingNeighborUpdater.java:47) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.server.level.ServerLevel.m_46672_(ServerLevel.java:966) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.server.level.ServerLevel.m_6289_(ServerLevel.java:1431) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.level.Level.markAndNotifyBlock(Level.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.level.Level.m_6933_(Level.java:224) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.level.Level.m_7731_(Level.java:188) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.m_230328_(StructureTemplate.java:236) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.thirdlife.iterrpg.procedures.GenericDungeonSpawnProcedure.execute(GenericDungeonSpawnProcedure.java:167) ~[iterpg-0.5.0-1.19.2.jar%23503!/:?]
	at net.thirdlife.iterrpg.block.GenericDungeonGenBlockBlock.m_213897_(GenericDungeonGenBlockBlock.java:70) ~[iterpg-0.5.0-1.19.2.jar%23503!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222963_(BlockBehaviour.java:694) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.server.level.ServerLevel.m_184112_(ServerLevel.java:645) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.ticks.LevelTicks.m_193272_(LevelTicks.java:215) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.world.ticks.LevelTicks.m_193225_(LevelTicks.java:98) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:276) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23627!/:?]
	... 5 more
[07Apr2024 21:04:13.001] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 515be5dd-11e4-4bf0-9185-dfbc16c5a037
[07Apr2024 21:04:13.002] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /root/Steampunk/./crash-reports/crash-2024-04-07_21.04.12-server.txt
[07Apr2024 21:04:13.003] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
`

### Reproduction Steps

1. Explore overworld
2. crash

### Crash Report or Log

Crash log: https://gist.github.com/ODevil97/477cc38b74166b40bfe6bf750666fefc
Debug log: https://gofile.io/d/ki9Iv4

### Operating System

Linux/Debian

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by chorbintime** [comment]
Iter RPG issue - update the mod if possible. If no update is available or if the update doesn't fix it, then report it to their mod developers.
