### ISSUE TITLE
Crash on world startup because of insolation config

### ISSUE THREAD

**Issue by LiamHaste** [LunaPixelStudios/SteamPunk#310]
### Describe the Bug

when i try to load into a world it crashes and says something about there should only be 0 arguments but there are two in the insolation config.

### Reproduction Steps

1. start a world
2.crash
3.
...

### Crash Report or Log

Description: Exception in server tick loop  com.momosoftworks.coldsweat.util.exceptions.ArgumentCountException: Error parsing insulation config for item fur_cap: Expected 0 arguments, but only got 2 	at com.momosoftworks.coldsweat.util.serialization.ConfigHelper.lambda$readItemInsulations$17(ConfigHelper.java:560) ~[ColdSweat-2.3-b03d.jar%23508!/:2.3-b03d] {re:classloading} 	at com.momosoftworks.coldsweat.util.serialization.ConfigHelper.readItemMap(ConfigHelper.java:491) ~[ColdSweat-2.3-b03d.jar%23508!/:2.3-b03d] {re:classloading} 	at com.momosoftworks.coldsweat.util.serialization.ConfigHelper.readItemInsulations(ConfigHelper.java:557) ~[ColdSweat-2.3-b03d.jar%23508!/:2.3-b03d] {re:classloading} 	at com.momosoftworks.coldsweat.config.ConfigSettings.lambda$static$98(ConfigSettings.java:353) ~[ColdSweat-2.3-b03d.jar%23508!/:2.3-b03d] {re:mixin,re:classloading} 	at com.momosoftworks.coldsweat.util.serialization.DynamicHolder.load(DynamicHolder.java:74) ~[ColdSweat-2.3-b03d.jar%23508!/:2.3-b03d] {re:mixin,re:classloading} 	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) ~[?:?] {} 	at com.momosoftworks.coldsweat.config.ConfigSettings.load(ConfigSettings.java:711) ~[ColdSweat-2.3-b03d.jar%23508!/:2.3-b03d] {re:mixin,re:classloading} 	at com.momosoftworks.coldsweat.common.event.LoadConfigSettings.onServerStarted(LoadConfigSettings.java:72) ~[ColdSweat-2.3-b03d.jar%23508!/:2.3-b03d] {re:classloading} 	at com.momosoftworks.coldsweat.common.event.__LoadConfigSettings_onServerStarted_ServerStartedEvent.invoke(.dynamic) ~[ColdSweat-2.3-b03d.jar%23508!/:2.3-b03d] {re:classloading,pl:eventbus:B} 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?] {} 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {} 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {} 	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:109) ~[forge-1.19.2-43.3.5-universal.jar%23760!/:?] {re:classloading} 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:629) ~[client-1.19.2-20220805.130853-srg.jar%23755!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23755!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A} 	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

### Operating System

windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

### Other Mods

none

**Comment by qwek1** [comment]
please try updating the cold sweat mod
